
name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
   
    steps:
     
      - uses: actions/checkout@v3
     
      - name: Run a one-line script
        run:
         make build
      - name: Run a one-line script
        run:
         make push
      
      - name: helm version
        run: helm version
   
      - name: minikube start
        run: 
         minikube start
      - name: helm install
        run:
         helm install dockimage benchtask/ --values benchtask/values.yaml
      
      
      - name: Sleep for 300 seconds
        uses: jakejarvis/wait-action@master
        with:
         time: 150s
         
      - name: get services
        run: kubectl get services
            
      - name: URL
        run:  curl $(minikube service dockimage --url)  
           
      - name: helm install bck end
        run:
         helm install dockimage benchtask/ --values benchtask/values.yaml
      
      - name: Sleep for 300 seconds
        uses: jakejarvis/wait-action@master
        with:
         time: 150s
         
      - name: get services
        run: kubectl get services

      - name: URL
        run:  curl $(minikube service dockimage --url)  
 
